# https://github.com/big-data-europe/docker-spark
# Spark 2.0.2 for Hadoop 2.7+ with OpenJDK 8
version: '2'
services:
  spark-master:
    image: bde2020/spark-master:2.0.2-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:2.0.2-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ../target:/app
      - ../data:/data:ro
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
